# Your web app name. Used to uniquely configure containers.
service: chat_app
# Your image host or container image name
image: baldipa3/chat_app
servers:
  - 82.29.178.12
registry:
  # The container registry server, if you're not using Docker Hub
  # server: ghcr.io / ...
  username: baldipa3
  password:
    secure: KAMAL_REGISTRY_PASSWORD
env:
  secret:
    secure: RAILS_MASTER_KEY
#Configure a custom healthcheck
healthcheck:
  path: /healthz
  port: 4000
  max_attempts: 7
  interval: 20s
